loja/estoque/urls.py
from django.urls import path
from .views import *


app_name = 'estoque'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('contato/', ContatoView.as_view(), name='contato'),
    path('todos-produtos/', TodosProdutosView.as_view(), name='todosProdutos'),
    path('produto/<slug:slug>/', ProdutoDetalheView.as_view(), name='produtoDetalhe'),
    path('addcarro-<int:prod_id>/', AddCarroView.as_view(), name='addcarro'),
    path('meu-carro/', MeuCarroView.as_view(), name='meucarro'),
    path('manipular-carro/<int:cp_id>/', ManipularView.as_view(), name='manipularcarro'),
    path('limpar-carro/', LimparCarroView.as_view(), name='limparcarro'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    
    path('pagamento/', PagamentoView.as_view(), name='pagamento'),

    path('registrar/', ClienteRegistrarView.as_view(), name='clienteregistrar'),
    path('sair/', ClienteSairView.as_view(), name='clientesair'),
    path('entrar/', ClienteEntrarView.as_view(), name='clienteentrar'),
    path('perfil/', ClientePerfilView.as_view(), name='clienteperfil'),
    path('perfil/pedido-<int:pk>/', ClientePedidoDetalheView.as_view(), name='clientepedidodetalhe'),
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    
    path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
    path('admin-pedido/<int:pk>/', AdminPedidoDetalheView.as_view(), name='adminpedidodetalhe'),
    path('admin-todos-pedidos/', AdminPedidoListaView.as_view(), name='adminpedidolista'),
    path('admin-pedido-<int:pk>-mudar/', AdminPedidoMudarStatusView.as_view(), name='adminpedidomudar'),
    path('pesquisar/', PesquisarView.as_view(), name='pesquisar'),
]

loja/loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('estoque.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loja/estoque/models.py
from distutils.command.upload import upload
from operator import mod
from django.db import models
from django.contrib.auth.models import User


class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.nome_completo


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    image = models.ImageField(upload_to='admins')
    tel = models.CharField(max_length=20)

    def __str__(self) :
        return self.user.username


class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self) :
        return self.titulo


class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='produtos')
    preco_mercado = models.PositiveIntegerField()
    venda = models.PositiveIntegerField()
    descricao = models.TextField()
    visualizacao = models.PositiveIntegerField(default=0)
    
    def __str__(self) :
        return self.titulo


class Carro(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return "Carro:"+str(self.id)


class CarroProduto(models.Model):
    carro = models.ForeignKey(Carro,on_delete=models.CASCADE)
    produto= models.ForeignKey(Produto,on_delete=models.CASCADE)
    avalizacao = models.PositiveIntegerField()   
    quantidade = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()
    
    def __str__(self) :
        return "Carro:"+str(self.carro.id) + "CarroProduto:"+str(self.id) 


PEDIDO_STATUS=(
    ("Pedido Recebido","Pedido Recebido"),
    ("Pedido Processado","Pedido Processado"),
    ("Pedido Caminho","Pedido Caminho"),
    ("Pedido Completado","Pedido Completado"),
    ("Pedido Cancelado","Pedido Cancelado"),
    
)

METODO_PAGAMENTO=(
    ("Dinheiro Na Entrega","Dinheiro Na Entrega"),
    ("Khalti","Khalti")
    
)

class Pedido_ordem(models.Model):
    carro = models.OneToOneField(Carro,on_delete=models.CASCADE)
    ordenado_por = models.CharField(max_length=200)

    endereco_envio = models.CharField(max_length=200)
    telefone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    subtotal = models.PositiveIntegerField()
    desconto = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    pedido_status = models.CharField(max_length=50, choices=PEDIDO_STATUS)
    criado_em = models.DateTimeField(auto_now_add=True)
    pagamento_metodo = models.CharField(max_length=20, choices=METODO_PAGAMENTO, default='Dinheiro Na Entrega')
    pagamento_completo = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self) :
        return "Pedido_ordem:"+str(self.id)

loja/templates/admin_paginas/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">    
</head>
<body>
    <div class="container">
        <a href="{% url 'estoque:adminhome' %}">Home</a>
        <a href="{% url 'estoque:adminpedidolista' %}">Todos Pedidos</a>
        <a href="{% url 'estoque:home' %}" target="_blank">Visitar Loja</a>


        
    </div>

    {% block content %}

    {% endblock content %}    
</body>
</html>

loja/templates/admin_paginas/adminhome.html
{% extends 'admin_paginas/adminbase.html' %}

<title>{% block title %} Administrador {% endblock title %}</title>



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>Pedidos Pendentes</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>ID Pedido</th>
                        <th>Cliente</th>
                       
                        <th>Data Pedido</th>
                        <th>Valor</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in pedidosPendentes %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'estoque:adminpedidodetalhe' pedido.id %}">#Pedido_ {{pedido.id}}</a></td>
                        <td>{{pedido.ordenado_por}}</td>
                        
                        <td>{{pedido.criado_em}}</td>
                        <td>{{pedido.total}}</td>
                        
                    </tr>




                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



</div>

{% endblock content %}    

loja/templates/admin_paginas/adminlogin.html
{% extends 'base.html' %}
{% block title %}Administrador {% endblock title %}

{% block content %}
<style>
   .errorlist{
      color: red;
      list-style: none;
   }
</style>
   <div class="container">           
      <div class="row">
          
          <div class="col-md-6 mx-auto">
            <h2>Formulario administrador</h2>    
            <form action="" method="POST">
               {% csrf_token %}

               {{ form.as_p }}
               <button class="btn-sm btn-success">Entrar</button>
               {% if error %}
                    <li style="color: red; list-style-type: none;">{{ error }}</li>     

               {% endif %}
                
            </form>
            <p>Se voce ainda nao e cadastrado? <a href="{% url 'estoque:clienteregistrar'%}{% if request.GET.next%}?next={{ request.GET.next }}{% endif %}">Clique aqui!</a> </p>


          </div>
        
      </div>   
   </div>
  

{% endblock %}

loja/templates/admin_paginas/adminpedidodetalhe.html
{% extends 'admin_paginas/adminbase.html' %}
{% load humanize %}
<title>{% block title %} Detalhes Pedidos {% endblock title %}</title>



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8 max-auto">
            <h3>Detalhes do pedido</h3>
            <hr>
            <p><span class="font-weight-bold"> <samp>Produto ID: </samp><samp>{{ pedido_obj.id}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Status do Pedido: </samp><samp>{{ pedido_obj.pedido_status}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Data Efetuado: </samp><samp>{{ pedido_obj.criado_em}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Informacao CLiente: </samp><samp>{{ pedido_obj.ordenado_por}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Telefone CLiente: </samp><samp>{{ pedido_obj.telefone}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Endereco CLiente: </samp><samp>{{ pedido_obj.endereco_envio}}</samp></p>
            <p><span class="font-weight-bold"> <samp>Email: </samp><samp>{{ pedido_obj.email}}</samp></p>
              <hr>
              <h4>Itens Do pedido</h4>
              <table class="table">
                  <thead>
                      <tr>
                          <th>Codigo</th>
                          <th>Item</th>
                          <th>Avalizacao</th>
                          <th>Quantidade</th>
                          <th>Subtotal</th>
                      </tr>
                  </thead>
                  <tbody>
                      {% for cp in pedido_obj.carro.carroproduto_set.all %}   
                          <tr>
                              <th>{{forloop.counter}}</th>
                              <th><a target="blank" href="{% url 'estoque:produtoDetalhe' cp.produto.slug%}"> {{cp.produto.titulo}}{{cp.produto.id}}</th></a>
                              <th>{{cp.avalizacao}}</th>
                              <th>{{cp.quantidade}}</th>
                              <th>{{cp.sub_total}}</th>
                          </tr>

                      {% endfor %}
                      <tr>
                          <th colspan="4" class="text-right"> Valor Total  </th>
                          <th>R$ .{{pedido_obj.total|intcomma }}</th>
                      </tr>
                      
                  </tbody>

              </table>
              <form action="{% url 'estoque:adminpedidomudar' pedido_obj.id %}" method="post">
                  {% csrf_token %}
                  <select name="status">
                      {% for i,j in  todosstatus%}
                        <option value="{{i}}" {% if i == pedido_obj.pedido_status %} selected {% endif %}>{{j}}</option>
                      {% endfor %}
                      
                  </select>
                  <button class="btn btn-success">Alterar status</button>
              </form>

        </div> 
    </div>
</div>

{% endblock content %}    

loja/templates/admin_paginas/adminpedidolista.html
{% extends 'admin_paginas/adminbase.html' %}
{% load humanize %}
<title>{% block title %} Detalhes Pedidos {% endblock title %}</title>



{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12 max-auto">
            <h2>Todos Pedidos</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>ID Pedido</th>
                        <th>Cliente</th>
                       
                        <th>Data Pedido</th>
                        <th>Valor</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in todospedidos %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'estoque:adminpedidodetalhe' pedido.id %}">#Pedido_ {{pedido.id}}</a></td>
                        <td>{{pedido.ordenado_por}}</td>
                        
                        <td>{{pedido.criado_em}}</td>
                        <td>{{pedido.total}}</td>
                        <td>{{pedido.pedido_status}}</td>
                        
                    </tr>




                    {% endfor %}
                </tbody>
            </table>
        </div> 
    </div>
</div>

{% endblock content %}    