loja/estoque/urls.py
from django.urls import path
from .views import *


app_name = 'estoque'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('sobre/', SobreView.as_view(), name='sobre'),
    path('contato/', ContatoView.as_view(), name='contato'),
    path('todos-produtos/', TodosProdutosView.as_view(), name='todosProdutos'),
    path('produto/<slug:slug>/', ProdutoDetalheView.as_view(), name='produtoDetalhe'),
    path('addcarro-<int:prod_id>/', AddCarroView.as_view(), name='addcarro'),
    path('meu-carro/', MeuCarroView.as_view(), name='meucarro'),
    path('manipular-carro/<int:cp_id>/', ManipularView.as_view(), name='manipularcarro'),
    path('limpar-carro/', LimparCarroView.as_view(), name='limparcarro'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    
    path('pagamento/', PagamentoView.as_view(), name='pagamento'),

    path('registrar/', ClienteRegistrarView.as_view(), name='clienteregistrar'),
    path('sair/', ClienteSairView.as_view(), name='clientesair'),
    path('entrar/', ClienteEntrarView.as_view(), name='clienteentrar'),
    path('perfil/', ClientePerfilView.as_view(), name='clienteperfil'),
    path('perfil/pedido-<int:pk>/', ClientePedidoDetalheView.as_view(), name='clientepedidodetalhe'),
    path('admin-login/', AdminLoginView.as_view(), name='adminlogin'),
    
    path('admin-home/', AdminHomeView.as_view(), name='adminhome'),
    path('admin-pedido/<int:pk>/', AdminPedidoDetalheView.as_view(), name='adminpedidodetalhe'),
    path('admin-todos-pedidos/', AdminPedidoListaView.as_view(), name='adminpedidolista'),
    path('admin-pedido-<int:pk>-mudar/', AdminPedidoMudarStatusView.as_view(), name='adminpedidomudar'),
    path('pesquisar/', PesquisarView.as_view(), name='pesquisar'),
]

loja/loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('estoque.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loja/estoque/models.py
from distutils.command.upload import upload
from operator import mod
from django.db import models
from django.contrib.auth.models import User


class Cliente(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    endereco = models.CharField(max_length=200, null=True, blank=True)
    data_cadastro = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return self.nome_completo


class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome_completo = models.CharField(max_length=200)
    image = models.ImageField(upload_to='admins')
    tel = models.CharField(max_length=20)

    def __str__(self) :
        return self.user.username


class Categoria(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self) :
        return self.titulo


class Produto(models.Model):
    titulo = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    categoria = models.ForeignKey(Categoria,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='produtos')
    preco_mercado = models.PositiveIntegerField()
    venda = models.PositiveIntegerField()
    descricao = models.TextField()
    visualizacao = models.PositiveIntegerField(default=0)
    
    def __str__(self) :
        return self.titulo


class Carro(models.Model):
    cliente = models.ForeignKey(Cliente,on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    criado_em = models.DateTimeField(auto_now_add=True)

    def __str__(self) :
        return "Carro:"+str(self.id)


class CarroProduto(models.Model):
    carro = models.ForeignKey(Carro,on_delete=models.CASCADE)
    produto= models.ForeignKey(Produto,on_delete=models.CASCADE)
    avalizacao = models.PositiveIntegerField()   
    quantidade = models.PositiveIntegerField()
    sub_total = models.PositiveIntegerField()
    
    def __str__(self) :
        return "Carro:"+str(self.carro.id) + "CarroProduto:"+str(self.id) 


PEDIDO_STATUS=(
    ("Pedido Recebido","Pedido Recebido"),
    ("Pedido Processado","Pedido Processado"),
    ("Pedido Caminho","Pedido Caminho"),
    ("Pedido Completado","Pedido Completado"),
    ("Pedido Cancelado","Pedido Cancelado"),
    
)

METODO_PAGAMENTO=(
    ("Dinheiro Na Entrega","Dinheiro Na Entrega"),
    ("Khalti","Khalti")
    
)

class Pedido_ordem(models.Model):
    carro = models.OneToOneField(Carro,on_delete=models.CASCADE)
    ordenado_por = models.CharField(max_length=200)

    endereco_envio = models.CharField(max_length=200)
    telefone = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    subtotal = models.PositiveIntegerField()
    desconto = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    pedido_status = models.CharField(max_length=50, choices=PEDIDO_STATUS)
    criado_em = models.DateTimeField(auto_now_add=True)
    pagamento_metodo = models.CharField(max_length=20, choices=METODO_PAGAMENTO, default='Dinheiro Na Entrega')
    pagamento_completo = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self) :
        return "Pedido_ordem:"+str(self.id)

loja/templates/addproCarro.html
{% extends 'base.html' %}
{% block title %}Carrinho {% endblock title %}

{% block content %}


<div class="container">
    produto adiciondo no carrinho
</div>

{% endblock %}

loja/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-success">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'estoque:home' %}">Loja</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                           
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% if request.user.cliente %}
                        <li><a class="dropdown-item" href="{% url 'estoque:clienteperfil' %}">Meu Perfil</a></li>
                    {% else %}
                        <li><a class="dropdown-item" href="{% url 'estoque:clienteregistrar' %}">Cadastrar Cliente</a></li>
                    {% endif %}
                  <li><hr class="dropdown-divider"></li>                  
                </ul>
              </li>

             
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'estoque:todosProdutos' %}">Categorias</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'estoque:meucarro' %}">Carrinho</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'estoque:contato' %}">Contato</a>
              </li>

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'estoque:sobre' %}">Sobre</a>
              </li>
              {% if request.user.cliente %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'estoque:clientesair' %}">Sair</a>
                </li>
              {% else %}   
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'estoque:clienteentrar' %}">Entrar</a>
                </li>
              {% endif %}
            </ul>

            <form class="d-flex" action="{% url 'estoque:pesquisar' %}" method="GET">
              <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search"  name="keyword">
              <button class="btn btn-warning" type="submit">Buscar</button>
            </form>

          </div>
        </div>
      </nav>
    <hr>
    {% block content %}

    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

loja/templates/clienteentrar.html
{% extends 'base.html' %}
{% block title %}Entrar {% endblock title %}

{% block content %}
<style>
   .errorlist{
      color: red;
      list-style: none;
   }
</style>
   <div class="container">           
      <div class="row">
          
          <div class="col-md-6 mx-auto">
            <h2>Entrar</h2>    
            <form action="" method="POST">
               {% csrf_token %}

               {{ form.as_p }}
               <button class="btn-sm btn-success">Entrar</button>
               {% if error %}
                    <li style="color: red; list-style-type: none;">{{ error }}</li>     

               {% endif %}
                
            </form>
            <p>Se voce ainda nao e cadastrado? <a href="{% url 'estoque:clienteregistrar'%}{% if request.GET.next%}?next={{ request.GET.next }}{% endif %}">Clique aqui!</a> </p>


          </div>
        
      </div>   
   </div>
  

{% endblock %}

loja/templates/clientepedidodetalhe.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}Detalhes do Pedido {% endblock title %}

{% block content %}

   <div class="container">           
      <div class="row">          
          <div class="col-md-8 max-auto">
              <h3>Detalhes do pedido</h3>
              <hr>
              <p><span class="font-weight-bold"> <samp>Produto ID: </samp><samp>{{ pedido_obj.id}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Status do Pedido: </samp><samp>{{ pedido_obj.pedido_status}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Data Efetuado: </samp><samp>{{ pedido_obj.criado_em}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Informacao CLiente: </samp><samp>{{ pedido_obj.ordenado_por}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Telefone CLiente: </samp><samp>{{ pedido_obj.telefone}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Endereco CLiente: </samp><samp>{{ pedido_obj.endereco_envio}}</samp></p>
              <p><span class="font-weight-bold"> <samp>Email: </samp><samp>{{ pedido_obj.email}}</samp></p>
                <hr>
                <h4>Itens Do pedido</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Item</th>
                            <th>Avalizacao</th>
                            <th>Quantidade</th>
                            <th>Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cp in pedido_obj.carro.carroproduto_set.all %}   
                            <tr>
                                <th>{{forloop.counter}}</th>
                                <th><a target="blank" href="{% url 'estoque:produtoDetalhe' cp.produto.slug%}"> {{cp.produto.titulo}}{{cp.produto.id}}</th></a>
                                <th>{{cp.avalizacao}}</th>
                                <th>{{cp.quantidade}}</th>
                                <th>{{cp.sub_total}}</th>
                            </tr>

                        {% endfor %}
                        <tr>
                            <th colspan="4" class="text-right"> Valor Total  </th>
                            <th>R$ .{{pedido_obj.total|intcomma }}</th>
                        </tr>
                        
                    </tbody>

                </table>
          </div>
        
      </div>   
   </div>
  

{% endblock %}

loja/templates/clienteperfil.html
{% extends 'base.html' %}
{% block title %}Perfil {% endblock title %}

{% block content %}

   <div class="container">           
      <div class="row">          
          <div class="col-md-8">
            <h2>Detalhes Do Cliente</h2>    
            <p><span class="font-weight-bold">Nome: </span>{{ cliente.nome_completo}}</p>
            <p><span class="font-weight-bold">Usuario: </span>{{ cliente.user.username}}</p>
            <p><span class="font-weight-bold">Email: </span>{{ cliente.user.email}}</p>
            <p><span class="font-weight-bold">Endereço: </span>{{ cliente.endereco}}</p>
            <p><span class="font-weight-bold">Cadastrado em: </span>{{ cliente.data_cadastro}}</p>
          </div>

          <div class="col-md-8">
              <br>
            <h2>Detalhes de Compras</h2>  
            <br>
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Pedido ID</th>
                        <th>Valor</th>
                        <th>Data Pedido</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pedido in pedidos %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            
                            <td><a href="{% url 'estoque:clientepedidodetalhe' pedido.pk %}">Pedido Numero: {{pedido.id}}</a></td>
                            <td>{{pedido.total}}</td>
                            <td>{{pedido.criado_em}}</td>
                            <td>{{pedido.pedido_status}}</td>
                        </tr>

                    {% endfor%}
                </tbody>
            </table>  
                                
          </div>
        
      </div>   
   </div>
  

{% endblock %}

loja/templates/clienteregistrar.html
{% extends 'base.html' %}
{% block title %}Registrar Clientes {% endblock title %}

{% block content %}
<style>
   .errorlist{
      color: red;
      list-style: none;
   }
</style>
   <div class="container">           
      <div class="row">
          
          <div class="col-md-6 mx-auto">
            <h2>Cadastrar clientes</h2>    
            <form action="" method="POST">
               {% csrf_token %}

               {{ form.as_p }}
               <button class="btn-sm btn-success">Cadastrar Cliente</button>
                
            </form>
            <p>Voce ja e cadastrtado? <a href="{% url 'estoque:clienteentrar'%}">Login</a> </p>

          </div>
        
      </div>   
   </div>
  

{% endblock %}

loja/templates/contato.html
{% extends 'base.html' %}
{% block title %}Contato {% endblock title %}

{% block content %}
   <h1>seja bem vindo pagina contato</h1> 
{% endblock %}

loja/templates/home.html
{% extends 'base.html' %}
{% block title %}Home {% endblock title %}

{% block content %}

   <div class="container"> 
      <h1 class="text-center">seja bem vindo pagina home</h1> 
      <hr>
      <div class="row mt-3">
         {% for p in produto_list %}
            <div class="col-md-3 card">
                  <div class="m-3">                     
                     <h4><a href="{% url 'estoque:produtoDetalhe' p.slug%}">{{p.titulo}}</a></h4>
                     <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 200px; object-fit: contain;">
                     <p class="mt-3">Preco: <strike>R$ .{{p.preco_mercado}}</strike>< R$. {{p.venda}}</p>
                     <a href="{% url 'estoque:addcarro' p.id %}" class="btn btn-success">Comprar</a>
           
               </div>
            </div>
         {% endfor %}

     <nav aria-label="...">
      <ul class="pagination">
         {% if produto_list.has_previous %}         
            <li class="page-item">
               <a class="page-link" href="?page={{ produto_list.previous_page_number }}">Anterior</a>
            </li>
         {% else %}
            <li class="page-item">
               <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Anterior</a>
            </li>
         {% endif %}
         {% for i in produto_list.paginator.page_range  %}
            {% if i == produto_list.number %}
               <li class="page-item active"><a class="page-link" >{{i}}</a></li>
            {% else %}
               <li class="page-item"> <a class="page-link" href="?page={{i}}">{{i}}</a></li>
            {% endif %}
         {% endfor %}

         {% if produto_list.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ produto_list.next_page_number }}">Proxima</a></li>
         {% else %}
            <li class="page-item disabled">
               <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Proxima</a>
            </li>
         {% endif %}
      </ul>
    </nav>


   </div>
  

{% endblock %}

loja/templates/meucarro.html
{% extends 'base.html' %}
{% block title %}Home {% endblock title %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>Codigo</th>
                        <th>Produto</th>
                        <th>Avalizacao</th>
                        <th>Quantidade</th>
                        <th>Subtotal</th>
                        <th>Acao</th>
                        
                    
                    </tr>
                    <tbody>
                        {% for cp in carro.carroproduto_set.all %}
                         <tr>
                             <td>{{ forloop.counter }}</td>
                             <td>{{ cp.produto.titulo }}</td>
                             <td>{{ cp.avalizacao }}</td>
                             <td>{{ cp.quantidade }}</td>
                             <td>{{ cp.sub_total }}</td>                             
                             <td>
                                 <a href="{% url 'estoque:manipularcarro' cp.id %}?acao=inc" class="btn btn-success">+</a>
                                 <a href="{% url 'estoque:manipularcarro' cp.id %}?acao=dcr" class="btn btn-warning">-</a>
                                 <a href="{% url 'estoque:manipularcarro' cp.id %}?acao=rmv" class="btn btn-danger">X</a>
                             </td>
                         </tr>   

                        {% endfor %}

                        <tr>
                            <th colspan="4" class="text-right">Carrinho Total  </th>
                            <th >R$ .{{ carro.total }}   </th>                            
                            {% if carro.carroproduto_set.all %}    
                                <th><a href="{% url 'estoque:limparcarro' %} " class="btn-sm btn-warning">Limpar Carrinho</a></th>                            
                            {% endif %}
                        </tr>
                        {% if carro.carroproduto_set.all %}    
                            <tr>                            
                                <th><a href="{% url 'estoque:checkout' %} " class="btn-sm btn-info">Processar Compra</a></th>                                                            
                            </tr>
                        {% endif %}
                    </tbody>
                </thead>
            </table>
        </div>
    </div>
</div>




{% endblock %}

loja/templates/pagamento.html
<h3>Pagina de pagamento</h3>

loja/templates/pesquisar.html
{% extends 'base.html' %}
{% block title %}Pesquisar Produtos {% endblock title %}

{% block content %}

   <div class="container">       
      <div class="row">
         
            <div class="col-md-12">
                  <h3>Resultado da Pesquisa <span class="text-success">{{request.GET.keyword}}</span></h3>
                  <hr>
                  {% for result in results %}
                        <div class="row">
                              <div class="col-md-4">
                                    <img src="{{result.image.url}}" class="img-fluid" alt="">
                              </div>

                              <div class="col-md-8">
                                    <h4><a href="{% url 'estoque:produtoDetalhe' result.slug %}"> {{result.titulo}}</a></h4>
                                    <p>{{result.descricao|truncatewords:50}}</p>
                                    <a href="{% url 'estoque:addcarro' result.id %}" class="btn btn-success">Comprar</a>
                              </div>                              
                        </div>
                  {% endfor %}
            </div>         
      </div>   
   </div>
  

{% endblock %}

loja/templates/processar.html
{% extends 'base.html' %}
{% block title %}Processar Compra {% endblock title %}

{% block content %}

   <div class="container"> 
      
      <div class="row">
           <div class="col-md-6">
               <h3>Item do carrinho</h3>
               <a href="{% url 'estoque:meucarro' %} " class="btn-sm btn-warning">Atualizar Carrinho</a>
               <table class="table">
                    <thead>
                        <tr>
                            <th>Codigo</th>
                            <th>Produto</th>
                            <th>Avalizacao</th>
                            <th>Quantidade</th>
                            <th>Subtotal</th>
                            <th>Acao</th>
                            
                        
                        </tr>
                    </thead>
                    <tbody>
                        {% for cp in carro.carroproduto_set.all %}
                         <tr>
                             <td>{{ forloop.counter }}</td>
                             <td>{{ cp.produto.titulo }}</td>
                             <td>{{ cp.avalizacao }}</td>
                             <td>{{ cp.quantidade }}</td>
                             <td>{{ cp.sub_total }}</td>       
                         </tr>
                         {% endfor %}
                    </tbody> 
                    <tr>
                        <th colspan="4" class="text-right">Valor Total</th>
                        <th>R$ . {{ carro.total }}</th>
                    </tr>
                </table>      

           </div>   
           <div class="col-md-6">
               <h3>Detalhes Produtos</h3>
               <form action=" " method="POST">
                   {% csrf_token %}

                   {{ form.as_p }}
                   <button class="btn-sm btn-info">Comprar</button>



               </form>
           </div>
            
      </div>   
   </div>
  

{% endblock %}

loja/templates/sobre.html
{% extends 'base.html' %}
{% block title %} Sobre{% endblock title %}
{% block content %}
   <h1>seja bem vindo pagina sobre</h1> 
   {% endblock %}

loja/templates/todosProdutos.html
{% extends 'base.html' %}
{% block title %}Todos Produtos {% endblock title %}

{% block content %}

   <div class="container"> 
      <h1 class="text-center">Todos produtos da categoria</h1> 

      {% for cat in todascategorias %}
        <h1>{{cat.titulo}}</h1>
        <div class="row mt-3">
            {% for p in cat.produto_set.all %}
               <div class="col-md-4">
                     <div class="m-3">
                        <h4><a href="{% url 'estoque:produtoDetalhe' p.slug%}">{{p.titulo}}</a></h4>
                        
                        <img src="{{p.image.url}}" alt="" class="img-fluid" style="height: 100px; object-fit: cover;">
                        <p class="mt-3">Preco: <strike>R$ .{{p.preco_mercado}}</strike>< R$. {{p.venda}}</p>                        
                        <a href="{% url 'estoque:addcarro' p.id %}" class="btn btn-success">Comprar</a>
                  </div>
               </div>
            {% endfor %}
         </div>   

         


      {% endfor %}
      
   </div>
  

{% endblock %}